language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1

env:
  - JEKYLL_VERSION=1.0
  - JEKYLL_VERSION=2.0

install:
  - bundle install

script:
  - bundle exec jekyll build --trace

notifications:
  email: false
