# Site settings
title: Beat the Banker!
email: andy.ernst@newgametown.com
description: "Beat the Banker! An addictive card game from New Game Town. Play it on your phone today!"
baseurl: ""
url: "http://www.beat-the-banker.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
